To stable
jeedom/plugin-htmldisplay pull request #14
Opened 2024-12-22 19:50 UTC by Caelion

MR To stable

2025-01-13 21:11 UTC, Caelion commented
Avez-vous des news pour la MR s'il vous plaît ?

2025-02-04 20:01 UTC, Caelion commented
@zoic21 : est-ce la bonne procédure pour le MR ou souhaites-tu (toi ou l'équipe Jeedom) une autre façon de faire ?

2025-02-05 08:33 UTC, zoic21 commented
Bonjour,
Je vais remonter le point a l'équipe pour voir comment faire.

2025-03-17 19:44 UTC, Caelion commented
Bonjour @zoic21 ,
Aurais tu des nouvelles de l'équipe pour la procédure s'il te plaît ?
Merci
Bien à toi,

2025-04-30 18:51 UTC, Caelion commented
Bonjour
Avez vous pu avancer sur le MR ?

2025-05-23 09:00 UTC, Mips2648 commented on core/class/htmldisplay.class.php
> + protected static $_widgetPossibility = array('custom' => true);
we can argue on the fact that property should be private or protected but today $_widgetPossibility is accessed directly by the core, so outside of the class; I would suggest to let it public as it is in plugin-template

2025-05-23 09:06 UTC, Mips2648 requested changes
PR should be done on beta branch, not master

2025-05-23 14:37 UTC, Caelion commented
Hello Mips
PR was already done in 2024 and merge on the beta branch on the 22th nov 2024
But nothing change after in master branch, that’s why I asked to merge on master as explained above

2025-05-23 16:23 UTC, Mips2648 commented
so we should merge from jeedom:beta iso caelion:beta to jeedom:master and

2025-05-23 16:26 UTC, Mips2648 commented
replace by https://github.com/jeedom/plugin-htmldisplay/pull/15

2025-05-23 16:26 UTC, closed without merging